# Generated by Django 2.1.5 on 2019-05-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190530_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cehck_num',
        ),
        migrations.RemoveField(
            model_name='users',
            name='check_pass',
        ),
    ]
